### PR TITLE
Force arena saving after load

### PR DESCRIPTION
**Pull request by FormallyMyles**
Fix critical bug which caused spawns to be wiped on reboot. This happens because the arena is saved on initialisation and this simply writes over that save.

### CODE REVIEW

**Review by jamierocks — APPROVED** [review]
Looking through the function of Arena#store, which was what I expected, I totally agree with these changes.

It would now be great to see @caseif take his look at this to ensure the storage wasn't deferred to a later point, and merge and make release as necessary.

**Comment by caseif** [comment]
I'm not seeing the problem here - under what circumstances is data erased? I can't reproduce the bug through some preliminary testing.

**Comment by FormallyMyles** [comment]
I replicated via the following:
1. Start server with no configs
2. Create an arena with no spawn points of TTT
3. Add a few spawn points
4. Look at arenas.json and the spawn points will be there
5. Reload
6. Spawn points will now be gone. If you turn off the server they are lost.

Hopefully this helps, this was tested with all the current versions prior to this patch. (From Bukkit)

**Comment by caseif** [comment]
Looking through the problematic code, this stems from the fact that arenas are inappropriately saved when loading due to use of unified construction code. I would prefer a solution which resolves this underlying issue, which I'll try to get out within the next hour or so.

That all being said, good catch here; I really appreciate the contribution.

**Pull request closed without merging**
